#!/usr/bin/env bash
# Display information about subdomains.

# define print_info function
show_info_subd()
{
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep "$2" | awk -v subd="$2" '{print "The subdomain " subd " is a " $4 " record and points to " $5}'
}

if [ $# -eq 1 ]
then
    for info in 'www' 'lb-01' 'web-01' 'web-02'
    do
        show_info_subd "$1" "$info"
    done
else
    show_info_subd "$1" "$2"
fi