#!/usr/bin/env bash
# Display information about subdomains.

# define show_info_subd function
show_info_subd () {
    reg_ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $reg_ip" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  show_info_subd "$1" "www"
  show_info_subd "$1" "lb-01"
  show_info_subd "$1" "web-01"
  show_info_subd "$1" "web-02"
elif [ "$#" == 2 ]
then
  show_info_subd "$1" "$2"
fi