#!/usr/bin/env bash
# Transfer a file from our client to a server.

# Check for the required number of arguments
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# execute scp with the args: 4)PATH_TO_FILE 1)IP 3)USERNAME 2)PATH_TO_SSH_KEY
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi