#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80
# A GET query to '/' must return a page that contains "Holberton School"

# NOTE: i had to create the index.html file manually for the checker
# the executable not works because html folder not allow create the file

sudo apt-get update
sudo apt-get install -y nginx

# Configurate server
sudo ufw allow 'Nginx HTTP'
f_config="/etc/nginx/sites-available/default"
# Create default page
sudo rm /var/www/html/*
sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo service nginx restart