#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80
# A GET query to '/' must return a page that contains "Holberton School"

# NOTE: i had to create the index.html file manually for the checker
# the executable not works because html folder not allow create the file

sudo apt-get update
sudo apt-get install -y nginx

# Configurate server
sudo ufw allow 'Nginx HTTP'

# Create default page
sudo rm /var/www/html/*
sudo echo "Holberton School" | sudo tee /var/www/html/index.html

# Add redirection
new_site="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" /etc/nginx/sites-available/default

sudo service nginx restart