#!/usr/bin/env bash

# Script that install NGINX, be listening on port 80 and must return
# a page that contains the string "Holberton School"
# if the user try to acces /redirect_me should be redirect to random page.
# if the user try to acces to not found page should be show "Ceci n'est pas une page"
# Customs headers. The name of the custom HTTP header must be X-Served-By.
# The value of the custom HTTP header must be the hostname of the server Nginx is running on.

apt-get update
apt-get install -y nginx

# Create default page
echo "Holberton School" > /var/www/html/index.html

# Configurate server
ufw allow 'Nginx HTTP'

f_config="/etc/nginx/sites-available/default"

# Add header
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" $f_config

# Add redirection
new_site="https://github.com/EstephaniaCalvoC/"
sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" $f_config

# Add 404 redirection
echo "Ceci n'est pas une page" > /usr/share/nginx/html/my_404.html
new_404="my_404.html"
l_new_404="/my_404.html {root /usr/share/nginx/html;\n internal;}"
sed -i "/listen 80 default_server/a error_page 404 /$new_404; location = $l_new_404" $f_config

service nginx restart