#!/usr/bin/env bash
# Script that fix conection on port 80 for the NGINX web server
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart