#!/usr/bin/env bash
#stops 4-to_infinity_and_beyond process.

pkill -f "$(4-to_infinity_and_beyond)"
#https://esgeeks.com/matar-procesos-linux-kill-pkill-killall/
#https://linuxize.com/post/pkill-command-in-linux/