#!/usr/bin/env bash
# Display Holberton School 10 times and at 9th line print Hi.

i=1
while ((i<11))
do
    if ((i==4))
    then
        echo "bad luck"
    elif ((i==8))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done